### ISSUE TITLE
Category dumper cleanup

### ISSUE THREAD

**Issue by simonepigazzini** [cms-analysis/flashgg#1174]
In the attempt to merge the STXS and differential PR (#1169 and #1166) these issues arose:

1) Do we really need to have the STXS splitting hardcoded inside the CategoryDumper, is
    there any show stopper to implement it using a CutBasedDumper instead?

2) Pdf and NNLOPS weights are also hardcoded inside the dumper class. Is this unavoidable or can       
    we write a producer that adds these weights to the TagTruth object and dump them from there?

**Comment by simonepigazzini** [comment]
@threiten

**Comment by simonepigazzini** [comment]
I think for the discussion we could profit from having a look at an example file from the STXS

**Comment by edjtscott** [comment]
Thanks for flagging these two issues, I put an example output workspace from workspaceStd with doStageOne switched on here [1].

The main difference from the "usual" workflow is that the STXS bin value is also dumped, and this is then used later on to split the outputs into files for each STXS process. The dumping of the categories allows one to dump categories named according to the target bin, rather than running a separate producer for each one. As far as I am aware this is the only substantive difference. 

Regarding the weights, I am sure the NNLOPS weights can (and should) be moved. The pdf weights I am not so sure, I am not expert and would have to look through the code in detail. 

Will discuss more tomorrow. 

[1] /eos/user/e/escott/HggLegacy/WorkspaceTest/ForPullRequestReview

**Comment by edjtscott** [comment]
The NNLOPS weights have now been fully factorised from here. I had a quick look and it's not clear that the STXS info in the pdf code can be removed, and anyway the current implementation has been merged into the default branch. I think we can close this issue - there is still something to be worked out regarding how the pdfs work with the useParentDataset info, but this is separate.

**Comment by simonepigazzini** [comment]
I Agree, this is address in #1188 .
