### ISSUE TITLE
MicroAOD size tuning

### ISSUE THREAD

**Issue by musella** [cms-analysis/flashgg#162]
Current content (as of phys14 v2 production) is ~50% of MiniAOD.

We need to achieve a factor 2.5 reduction in order to meet the goal 1/5 goal.

I made a small excercie to see what could be done to meet the target.
https://musella.web.cern.ch/musella/higgs/flashgg/miniAOD.xls

Summary is that we need to:
- avoid photon info duplication in di-photon
- we should preselect leptons
- drop cluster information and store subset in photons
- only store photon ID info for vertexes associated with at least one di-photon pair
- reduce size of jet collection

**Comment by sethzenz** [comment]
This is a nice study and I think it is all realistically achievable!  A few general principles, to remind everyone, as we work on this:
* All slimming and preselection that targets event size should be configurable. The slimming should be performed at separate steps from producers.
* Tag producers should NEVER count on particular objects having been preselected, with the exception of specifically-labeled preselected collections for the analysis, e.g. preselected diphotons.
The logic here is that we want to be able to "put back" extra information for validation and debugging, and we want to be sure that the behavior of the analysis does not change when we do this.

**Comment by sethzenz** [comment]
Note that #27 is part of this task.

**Comment by sethzenz** [comment]
Here is an absolutely huge item that was added at some point in the past:
PileupSummaryInfos_addPileupInfo__HLT. 14760.9 5335.92

**Comment by sethzenz** [comment]
Here are the biggest offenders after the developments in PR #274, ignoring collections that we'll ultimately be able to remove once preselections are finalized.  This is for 50 ns ttH(gg): 

    flashggJets_selectedFlashggJets__FLASHggMicroAOD. 11386.4 1767.89
    flashggElectrons_selectedFlashggElectrons__FLASHggMicroAOD. 4440.14 1657.91
    PileupSummaryInfos_addPileupInfo__HLT. 4602.5 1640.32
    flashggPhotons_flashggSlimmedPhotonAndDiPhoton__FLASHggMicroAOD. 5046.86 1460.78
    flashggMuons_selectedFlashggMuons__FLASHggMicroAOD. 2974.24 1345.57
    recoCaloClusters_reducedEgamma_reducedEBEEClusters_PAT. 2964.51 1267.16
    recoSuperClusters_reducedEgamma_reducedSuperClusters_PAT. 3021.95 1028.47
    recoGenJets_slimmedGenJets__PAT. 3463.25 815.546
    recoVertexs_offlineSlimmedPrimaryVertices__PAT. 1276.1 700.128
    recoCaloClusters_reducedEgamma_reducedESClusters_PAT. 1926.52 586.901
    recoGenParticles_flashggPrunedGenParticles__FLASHggMicroAOD. 2332.33 500.446
    patMETs_slimmedMETs__PAT. 1064.44 384.924

Note PileupSummaryInfos is much smaller than in the last comment, because it was for 50 ns.  It will also be greatly shrunk by task #269.

Beyond that, the big things we can do:
   * Tighten preselections where possible.
   * Identify what we really need reducedEgamma for and cache those variables, then remove those collections.  Rerunning the egamma reduction is not possible on its own output, and as I understand it we are now keeping clusters that correspond to photons and electrons that we're removing from the event.

**Comment by sethzenz** [comment]
After the latest update to #274, further shrunk the final photon collection:

    flashggPhotons_flashggSlimmedPhotonAndDiPhoton__FLASHggMicroAOD. 2995.14 1258.37

**Comment by sethzenz** [comment]
#290 and #291  added a bit of size per event, due to the non-0th vertex jet collections:

0th vertex, always filled: 

    flashggJets_selectedFlashggPFCHSJets0__FLASHggMicroAOD. 11446 1780.54

First non-0th vertex needed by a diphoton, sometimes filled:

    flashggJets_selectedFlashggPFCHSJets1__FLASHggMicroAOD. 1596.92 332.446

Second non-0th vertex needed by a diphoton, rarely filled (2/1000 events):

    flashggJets_selectedFlashggPFCHSJets2__FLASHggMicroAOD. 802.792 185.832

These are always empty but still use space:

    flashggJets_selectedFlashggPFCHSJets3__FLASHggMicroAOD. 782.911 178.486
    flashggJets_selectedFlashggPFCHSJets4__FLASHggMicroAOD. 782.911 178.486

**Comment by sethzenz** [comment]
We were at 11.5 kB/evt (for 50 ns ttH) after #285, but now back to 12.4 kB/evt.  More to be done!  Possibilities to shrink jets:

* Only store pujetid info for the relevant vertex in vertex-specific collections like PFCHS
* 4 collections instead of 5 ??? (will raise an exception if we ever need more than there are)
* Don't keep 0th vertex if no diphoton points to it ??? (will make many studies difficult!)

**Comment by sethzenz** [comment]
I implemented the pujetid for relevant vertices only, but compared with the status q

**Comment by sethzenz** [comment]
I implemented the code for the first bullet point in the last comment (removing pujetid for vertices from diphotons other than the relevant one).  However it only saves 8 (ttH) or 10 (ggH) bytes per event.  I don't think it's worth it to change/test the code for that savings, but the code is here for the record: https://github.com/sethzenz/flashgg/blob/topic-pujetid-only-when-needed/MicroAOD/plugins/JetProducer.cc
